using System;
using System.Collections.Generic;

#nullable disable

namespace SiscomData.Models
{
    public partial class Tempconciliadopago
    {
        public string ComVersion { get; set; }
        public string ComEtiquetaComplemento { get; set; }
        public string ComTipoDocumento { get; set; }
        public string ComTipoDocumentoEmpresa { get; set; }
        public string ComSerie { get; set; }
        public int? ComFolio { get; set; }
        public string ComNoCertificado { get; set; }
        public string ComSubtotal { get; set; }
        public string ComTotal { get; set; }
        public string PagVersion { get; set; }
        public DateTime? PagFechaPago { get; set; }
        public string PagFormaDePagoP { get; set; }
        public string PagMonedaP { get; set; }
        public string PagTipoCambioP { get; set; }
        public string PagNumeroOperacion { get; set; }
        public decimal? PagMonto { get; set; }
        public string PagRfcemisorCtaOrd { get; set; }
        public string PagNomBancoOrdEx { get; set; }
        public string PagCtaOrdenante { get; set; }
        public string PagRfcemisorCtaBen { get; set; }
        public string PagNomBancoBen { get; set; }
        public string PagCtaBeneficiario { get; set; }
        public string PagTipoCadPago { get; set; }
        public string PagCertPago { get; set; }
        public string PagCadPago { get; set; }
        public string PagSelloPago { get; set; }
        public decimal? ImpTotalDeImpuestosRetenidos { get; set; }
        public decimal? ImpTotalDeImpuestosTrasladados { get; set; }
        public string PagRazonSocialEmisor { get; set; }
        public string PagRfcEmisor { get; set; }
        public string PagRegimen { get; set; }
        public string PagRegimenFiscal { get; set; }
        public string PagRazonSocialReceptor { get; set; }
        public string PagRfcReceptor { get; set; }
        public string PagUsoCfdi { get; set; }
        public string PagEmailReceptor { get; set; }
        public string PagLugarExpedicionSat { get; set; }
        public string PagLugarExpedicionGrafico { get; set; }
        public string PagAmbiente { get; set; }
        public string GraTipoDocumentoGra { get; set; }
        public string GraIfai { get; set; }
        public string GraFechaImpresaDelDocumento { get; set; }
        public string GraLeyenda1 { get; set; }
        public string GraLeyenda2 { get; set; }
        public string GrlImpresora { get; set; }
        public string GrlReimprime { get; set; }
        public string GrlUsuarioRealizoDocumento { get; set; }
        public short? GrlCopias { get; set; }
        public string GrlTipoAddenda { get; set; }
        public string GrlNombreAddenda { get; set; }
        public string Procesado { get; set; }
        public string ReferenciaInterna { get; set; }
        public string TipoComplemento { get; set; }
        public int? IdBancoComplemento { get; set; }
        public DateTime? FechaProcesado { get; set; }
        public string Usuario { get; set; }
        public DateTime? FechaAudit { get; set; }
        public short? Ccsucursal { get; set; }
        public int? Cliente { get; set; }
        public int? NoDocumento { get; set; }
        public string Numparcialidad { get; set; }
        public string Rfc { get; set; }
        public string NombreCliente { get; set; }
        public string Referencia { get; set; }
        public string Clave { get; set; }
        public string TipoPago { get; set; }
        public string NoPago { get; set; }
        public decimal? Importe { get; set; }
        public decimal? ImporteDlls { get; set; }
        public decimal? TipoCambio { get; set; }
        public int? IdBanco { get; set; }
        public int? SucOrigen { get; set; }
        public decimal? Cargopesos { get; set; }
        public decimal? AbonosPesos { get; set; }
        public decimal? CargosDolares { get; set; }
        public decimal? AbonosDolares { get; set; }
        public string Uuid { get; set; }
        public decimal? ImporteDocto { get; set; }
        public decimal? ImporteDoctoDlls { get; set; }
        public DateTime? FechaFactura { get; set; }
        public decimal? ImporteDr { get; set; }
        public string MetodoPagoDr { get; set; }
        public string MonedaDr { get; set; }
        public string TipoCambioDr { get; set; }
        public decimal? ImpSaldoAnt { get; set; }
        public decimal? ImpSaldoInsoluto { get; set; }
        public short? Area { get; set; }
        public short? Sucursal { get; set; }
        public string NombreSuc { get; set; }
        public string TipoSucursal { get; set; }
        public string MarcaExcel { get; set; }
        public short? PoliticaVentas { get; set; }
        public int? Ccplanta { get; set; }
        public int? Ccagrupacion { get; set; }
        public string DiaPedido { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono { get; set; }
        public string Ccelectrodos { get; set; }
        public double? Iva { get; set; }
        public string Prochemex { get; set; }
        public int? DiaSurtimiento { get; set; }
        public string SerieFactura { get; set; }
        public short? Ruta { get; set; }
        public string Nacional { get; set; }
        public string MatrizMetro { get; set; }
        public short? Agrupadas { get; set; }
        public bool? Impuestos { get; set; }
        public string NombrePta { get; set; }
        public short? Procesar { get; set; }
        public string Email { get; set; }
        public string BajaSucursal { get; set; }
        public DateTime? FechaAlta { get; set; }
        public string NumExt { get; set; }
        public string NumInt { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string LocationNomina { get; set; }
        public string Marcacion { get; set; }
        public DateTime? FechaBaja { get; set; }
        public string TipoTransmision { get; set; }
        public string CcSap { get; set; }
        public string Categoria { get; set; }
        public string CcSapAcetileno { get; set; }
        public string CcSapOxidom { get; set; }
        public string Fenuevos { get; set; }
        public bool? SucFrontera { get; set; }
        public bool? CentroMantto { get; set; }
        public bool? PermisoE01 { get; set; }
        public bool? SucSap { get; set; }
        public bool? TransmiteComisiones { get; set; }
        public short? Ccnodo { get; set; }
        public string TipoEmpaque { get; set; }
        public bool? ControlIngresoCaja { get; set; }
        public decimal? ImpPagado { get; set; }
        public string SerieDocto { get; set; }
        public int? FolioDocto { get; set; }
    }
}
